# Generated by Django 5.1.2 on 2024-10-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('category', models.CharField(choices=[('corruption', 'Corruption'), ('embezzlement', 'Embezzlement'), ('infrastructure', 'Infrastructure'), ('education', 'Education')], max_length=50)),
                ('county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Migori', 'Migori')], max_length=50)),
            ],
        ),
    ]
