# Generated by Django 5.1.2 on 2024-10-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_created_at_feedback_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
