# Generated by Django 5.1.2 on 2024-10-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
