# Generated by Django 5.1.2 on 2024-10-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_feedback_sentiment_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Migori', 'Migori'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Nyeri', 'Nyeri'), ('Kakamega', 'Kakamega'), ('Wajir', 'Wajir'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('West Pokot', 'West Pokot'), ('Kirinyaga', 'Kirinyaga'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Nile', 'West Nile'), ('Laikipia', 'Laikipia')], max_length=50),
        ),
    ]
