# Generated by Django 5.1.2 on 2024-10-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedback_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('corruption', 'Corruption'), ('embezzlement', 'Embezzlement'), ('infrastructure', 'Infrastructure'), ('education', 'Education'), ('crime', 'Crime'), ('violence', 'Violence'), ('housing', 'Housing'), ('business', 'Business'), ('pension', 'Pension'), ('health', 'Health'), ('security', 'Security'), ('environment', 'Environment'), ('transport', 'Transport')], max_length=50),
        ),
    ]
