# Generated by Django 5.1.2 on 2024-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedback_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
